package com.example.ui.components

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.CameraAlt
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Collections
import androidx.compose.material.icons.filled.PhotoCamera
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import androidx.core.content.FileProvider
import com.example.R
import com.example.data.model.FloorInspectionEntity
import com.example.data.model.FloorObservationEntity
import com.example.service.ai.AiVisionService
import com.example.service.ai.VisionResult
import com.example.util.ImageCompressionUtils
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DefectCaptureModal(
    floor: FloorInspectionEntity,
    aiService: AiVisionService,
    aiProvider: String,
    apiKey: String,
    language: String,
    initialPhotoPath: String? = null,
    observationToEdit: FloorObservationEntity? = null,
    autoLaunchCamera: Boolean = false,
    onDismiss: () -> Unit,
    onSaveDefect: (photoUrl: String?, observation: String, isAiGenerated: Boolean) -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    var selectedBitmap by remember {
        mutableStateOf<Bitmap?>(null)
    }
    var selectedPhotoUrl by remember {
        mutableStateOf<String?>(observationToEdit?.photoUrl ?: floor.photoUrl)
    }
    var observationText by remember {
        mutableStateOf(observationToEdit?.description ?: floor.observation)
    }
    var isAnalyzing by remember { mutableStateOf(false) }
    var isAiGenerated by remember {
        mutableStateOf(observationToEdit?.isAiGenerated ?: floor.isAiGenerated)
    }
    var statusFeedback by remember { mutableStateOf<String?>(null) }

    // Temp file & URI for camera capture
    var tempCameraUri by remember { mutableStateOf<Uri?>(null) }
    var tempCameraFile by remember { mutableStateOf<File?>(null) }

    fun processBitmapWithAi(bitmap: Bitmap, photoUrl: String, hint: String? = null) {
        selectedBitmap = bitmap
        selectedPhotoUrl = photoUrl
        isAnalyzing = true
        statusFeedback = "Analyse de l'anomalie en cours par Vision AI..."

        scope.launch {
            val result = aiService.analyzeDefectPhoto(
                bitmap = bitmap,
                provider = aiProvider,
                apiKey = apiKey,
                language = language,
                fallbackHint = hint
            )

            isAnalyzing = false
            when (result) {
                is VisionResult.Success -> {
                    observationText = result.summary
                    isAiGenerated = true
                    statusFeedback = if (result.isFromLiveAi) {
                        "✨ Analyse Vision AI terminée !"
                    } else {
                        "✨ Reconnaissance d'anomalie complétée"
                    }
                }
                is VisionResult.Error -> {
                    if (result.fallbackSummary != null) {
                        observationText = result.fallbackSummary
                        isAiGenerated = true
                        statusFeedback = "Suggestion IA appliquée (${result.message})"
                    } else {
                        statusFeedback = "Erreur: ${result.message}"
                    }
                }
            }
        }
    }

    // Camera launcher with automatic compression
    val cameraLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.TakePicture()
    ) { success ->
        if (success && tempCameraFile != null && tempCameraFile!!.exists()) {
            val compressed = ImageCompressionUtils.compressAndSaveImage(context, tempCameraFile!!)
            val bitmap = ImageCompressionUtils.decodeThumbnail(compressed.absolutePath, 800, 800)
                ?: BitmapFactory.decodeFile(compressed.absolutePath)
            if (bitmap != null) {
                processBitmapWithAi(bitmap, compressed.absolutePath, hint = "chantier")
            }
        }
    }

    // Safe launch camera after permission verified
    fun launchCameraInternal() {
        try {
            val imageFile = File(context.cacheDir, "camera_${System.currentTimeMillis()}.jpg")
            tempCameraFile = imageFile
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                imageFile
            )
            tempCameraUri = uri
            cameraLauncher.launch(uri)
        } catch (e: Exception) {
            statusFeedback = "Erreur caméra: ${e.localizedMessage}"
            Toast.makeText(context, "Erreur caméra: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    // Camera permission launcher
    val cameraPermissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission()
    ) { isGranted ->
        if (isGranted) {
            launchCameraInternal()
        } else {
            statusFeedback = "Permission caméra requise pour capturer une photo"
            Toast.makeText(context, "Permission caméra refusée", Toast.LENGTH_SHORT).show()
        }
    }

    fun requestCameraAndLaunch() {
        if (ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED) {
            launchCameraInternal()
        } else {
            cameraPermissionLauncher.launch(Manifest.permission.CAMERA)
        }
    }

    // Auto-launch camera or load initialPhotoPath / existing photo
    LaunchedEffect(initialPhotoPath, autoLaunchCamera, observationToEdit) {
        if (!initialPhotoPath.isNullOrBlank()) {
            val rawFile = File(initialPhotoPath)
            if (rawFile.exists()) {
                val compressed = ImageCompressionUtils.compressAndSaveImage(context, rawFile)
                val bitmap = ImageCompressionUtils.decodeThumbnail(compressed.absolutePath, 800, 800)
                    ?: BitmapFactory.decodeFile(compressed.absolutePath)
                if (bitmap != null) {
                    processBitmapWithAi(bitmap, compressed.absolutePath, hint = "chantier")
                }
            }
        } else if (autoLaunchCamera) {
            requestCameraAndLaunch()
        } else if (selectedBitmap == null) {
            val targetUrl = observationToEdit?.photoUrl ?: floor.photoUrl
            if (!targetUrl.isNullOrBlank()) {
                val bitmap = ImageCompressionUtils.decodeThumbnail(targetUrl, 800, 800)
                    ?: if (File(targetUrl).exists()) BitmapFactory.decodeFile(targetUrl) else null
                if (bitmap != null) {
                    selectedBitmap = bitmap
                }
            }
        }
    }

    // Gallery picker launcher with automatic image compression
    val galleryLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia()
    ) { uri: Uri? ->
        if (uri != null) {
            try {
                val inputStream = context.contentResolver.openInputStream(uri)
                val rawTemp = File(context.cacheDir, "gallery_raw_${System.currentTimeMillis()}.jpg")
                rawTemp.outputStream().use { out -> inputStream?.copyTo(out) }
                val compressed = ImageCompressionUtils.compressAndSaveImage(context, rawTemp)
                rawTemp.delete()

                val bitmap = ImageCompressionUtils.decodeThumbnail(compressed.absolutePath, 800, 800)
                    ?: BitmapFactory.decodeFile(compressed.absolutePath)
                if (bitmap != null) {
                    processBitmapWithAi(bitmap, compressed.absolutePath, hint = "chantier")
                }
            } catch (e: Exception) {
                statusFeedback = "Erreur lecture image: ${e.localizedMessage}"
            }
        }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = com.example.ui.theme.TwitterWhite,
        modifier = Modifier
            .fillMaxWidth()
            .testTag("defect_capture_modal"),
        title = {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text(
                        text = if (observationToEdit != null) "Modifier l'observation" else "Ajouter une observation",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = com.example.ui.theme.TwitterTextPrimary
                    )
                    Text(
                        text = "${floor.floorNumber} • Constat avec photo",
                        style = MaterialTheme.typography.bodySmall,
                        color = com.example.ui.theme.TwitterTextSecondary
                    )
                }
                Surface(
                    color = com.example.ui.theme.TwitterRedLight,
                    shape = RoundedCornerShape(6.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, com.example.ui.theme.TwitterRed.copy(alpha = 0.3f))
                ) {
                    Text(
                        text = "NON-CONFORME",
                        fontSize = 10.sp,
                        fontWeight = FontWeight.Bold,
                        color = com.example.ui.theme.TwitterRed,
                        modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp)
                    )
                }
            }
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState())
            ) {
                // Photo Preview Area
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(180.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(com.example.ui.theme.TwitterBackground)
                        .border(1.dp, com.example.ui.theme.TwitterBorder, RoundedCornerShape(12.dp)),
                    contentAlignment = Alignment.Center
                ) {
                    if (selectedBitmap != null) {
                        Image(
                            bitmap = selectedBitmap!!.asImageBitmap(),
                            contentDescription = "Défaut capturé",
                            modifier = Modifier.fillMaxWidth(),
                            contentScale = ContentScale.Crop
                        )
                    } else {
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            modifier = Modifier.padding(16.dp)
                        ) {
                            Icon(
                                Icons.Default.CameraAlt,
                                contentDescription = null,
                                tint = com.example.ui.theme.TwitterBlue,
                                modifier = Modifier.size(36.dp)
                            )
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(
                                text = "Prenez ou sélectionnez une photo du problème",
                                style = MaterialTheme.typography.bodySmall,
                                color = com.example.ui.theme.TwitterTextSecondary,
                                fontWeight = FontWeight.Medium
                            )
                        }
                    }

                    // AI Analyzing Overlay
                    if (isAnalyzing) {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(180.dp)
                                .background(Color.Black.copy(alpha = 0.7f)),
                            contentAlignment = Alignment.Center
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                CircularProgressIndicator(
                                    color = com.example.ui.theme.TwitterBlue,
                                    modifier = Modifier.size(36.dp),
                                    strokeWidth = 3.dp
                                )
                                Spacer(modifier = Modifier.height(10.dp))
                                Text(
                                    text = "Analyzing defect with AI...",
                                    color = Color.White,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 13.sp
                                )
                                Text(
                                    text = "Reconnaissance visuelle de l'anomalie",
                                    color = Color(0xFFCBD5E1),
                                    fontSize = 11.sp
                                )
                            }
                        }
                    }
                }

                Spacer(modifier = Modifier.height(12.dp))

                // Capture Actions Row
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    // Snap photo button
                    Button(
                        onClick = { requestCameraAndLaunch() },
                        modifier = Modifier
                            .weight(1f)
                            .testTag("snap_photo_btn"),
                        colors = ButtonDefaults.buttonColors(containerColor = com.example.ui.theme.TwitterBlue),
                        shape = RoundedCornerShape(20.dp)
                    ) {
                        Icon(Icons.Default.PhotoCamera, contentDescription = null, modifier = Modifier.size(16.dp), tint = Color.White)
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Caméra", fontSize = 12.sp, fontWeight = FontWeight.SemiBold, color = Color.White)
                    }

                    // Gallery button
                    OutlinedButton(
                        onClick = {
                            galleryLauncher.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
                        },
                        modifier = Modifier
                            .weight(1f)
                            .testTag("gallery_photo_btn"),
                        colors = ButtonDefaults.outlinedButtonColors(contentColor = com.example.ui.theme.TwitterBlue),
                        border = androidx.compose.foundation.BorderStroke(1.dp, com.example.ui.theme.TwitterBorder),
                        shape = RoundedCornerShape(20.dp)
                    ) {
                        Icon(Icons.Default.Collections, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Galerie", fontSize = 11.sp, fontWeight = FontWeight.SemiBold)
                    }
                }

                Spacer(modifier = Modifier.height(10.dp))

                // Fast Emulator Test Samples
                Text(
                    text = "OU tester avec un échantillon de chantier réel :",
                    style = MaterialTheme.typography.labelSmall,
                    color = com.example.ui.theme.TwitterTextSecondary,
                    fontWeight = FontWeight.SemiBold
                )

                Spacer(modifier = Modifier.height(6.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    val sample1 = Triple(R.drawable.defect_plinthe_1789325971550, "Plinthe", "plinthe")
                    val sample2 = Triple(R.drawable.defect_fissure_1789325982782, "Fissure", "fissure")
                    val sample3 = Triple(R.drawable.defect_peinture_1789325994752, "Peinture", "peinture")

                    listOf(sample1, sample2, sample3).forEach { (resId, label, hint) ->
                        Surface(
                            modifier = Modifier
                                .weight(1f)
                                .clip(RoundedCornerShape(8.dp))
                                .border(1.dp, com.example.ui.theme.TwitterBorder, RoundedCornerShape(8.dp))
                                .clickable {
                                    val bitmap = BitmapFactory.decodeResource(context.resources, resId)
                                    if (bitmap != null) {
                                        processBitmapWithAi(bitmap, "drawable://$resId", hint = hint)
                                    }
                                },
                            color = com.example.ui.theme.TwitterWhite
                        ) {
                            Column(
                                modifier = Modifier.padding(6.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                Image(
                                    painter = painterResource(id = resId),
                                    contentDescription = label,
                                    modifier = Modifier
                                        .size(36.dp)
                                        .clip(RoundedCornerShape(4.dp)),
                                    contentScale = ContentScale.Crop
                                )
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    text = label,
                                    fontSize = 10.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = com.example.ui.theme.TwitterTextPrimary
                                )
                            }
                        }
                    }
                }

                Spacer(modifier = Modifier.height(12.dp))

                // Observation Field (Auto-populated by AI & editable by user)
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = "Observation du défaut (IA) :",
                        style = MaterialTheme.typography.titleSmall,
                        fontWeight = FontWeight.Bold,
                        color = com.example.ui.theme.TwitterTextPrimary
                    )
                    if (isAiGenerated) {
                        Surface(
                            color = com.example.ui.theme.TwitterBlueLight,
                            shape = RoundedCornerShape(4.dp)
                        ) {
                            Row(
                                modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Icon(
                                    Icons.Default.AutoAwesome,
                                    contentDescription = null,
                                    tint = com.example.ui.theme.TwitterBlue,
                                    modifier = Modifier.size(11.dp)
                                )
                                Spacer(modifier = Modifier.width(3.dp))
                                Text(
                                    text = "Auto-rempli par IA",
                                    fontSize = 10.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = com.example.ui.theme.TwitterBlue
                                )
                            }
                        }
                    }
                }

                Spacer(modifier = Modifier.height(4.dp))

                OutlinedTextField(
                    value = observationText,
                    onValueChange = {
                        observationText = it
                    },
                    placeholder = { Text("Ex: Manque plinthe, Peinture écaillée, Fissure sur enduit...") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .testTag("defect_observation_input"),
                    shape = RoundedCornerShape(10.dp),
                    minLines = 2,
                    maxLines = 4
                )

                // Status message
                AnimatedVisibility(visible = statusFeedback != null) {
                    Text(
                        text = statusFeedback ?: "",
                        style = MaterialTheme.typography.bodySmall,
                        color = com.example.ui.theme.TwitterTextSecondary,
                        fontSize = 11.sp,
                        modifier = Modifier.padding(top = 4.dp)
                    )
                }

                // Quick defect chip suggestions
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = "Suggestions rapides :",
                    style = MaterialTheme.typography.labelSmall,
                    color = com.example.ui.theme.TwitterTextSecondary
                )
                Spacer(modifier = Modifier.height(4.dp))
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    listOf("Manque plinthe", "Peinture écaillée", "Fissure sur enduit").forEach { suggestion ->
                        Surface(
                            shape = RoundedCornerShape(12.dp),
                            color = com.example.ui.theme.TwitterBackground,
                            border = androidx.compose.foundation.BorderStroke(1.dp, com.example.ui.theme.TwitterBorder),
                            modifier = Modifier.clickable {
                                observationText = suggestion
                                isAiGenerated = true
                            }
                        ) {
                            Text(
                                text = suggestion,
                                fontSize = 10.sp,
                                fontWeight = FontWeight.Medium,
                                color = com.example.ui.theme.TwitterTextPrimary,
                                modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp)
                            )
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val obs = if (observationText.isNotBlank()) observationText else "Défaut non spécifié"
                    onSaveDefect(selectedPhotoUrl, obs, isAiGenerated)
                },
                colors = ButtonDefaults.buttonColors(containerColor = com.example.ui.theme.TwitterBlue),
                shape = RoundedCornerShape(20.dp),
                modifier = Modifier.testTag("save_defect_btn")
            ) {
                Icon(Icons.Default.Check, contentDescription = null, modifier = Modifier.size(16.dp))
                Spacer(modifier = Modifier.width(4.dp))
                Text(if (observationToEdit != null) "Mettre à jour" else "Enregistrer l'observation", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Annuler", color = com.example.ui.theme.TwitterTextSecondary, fontWeight = FontWeight.SemiBold)
            }
        }
    )
}
